#!/bin/bash
#
# Emits (to stdout) a Helm values fragment that enables EVERY package declared
# by the catalog index, for the cluster-based sanity-plugins deployment:
#
#   global:
#     dynamic:
#       plugins:
#         - package: "<each declared ref>"
#           disabled: false
#
# Merged UNDER the curated values via `helm::merge_values merge` (fragment as
# base, curated file as diff), so curated entries keep their pluginConfig while
# every other index package gets enabled dynamically. This replaces the frozen
# hand-maintained plugin list: the enabled set now follows the index passed via
# CATALOG_INDEX_IMAGE (e.g. an RC index through Gangway --catalog-index-image).
#
# When a curated values file is passed as $2, index packages whose NAME already
# appears there are omitted from the fragment. Dedup by exact ref is not
# enough: curated entries pin old tags, so the same plugin under a newer index
# ref would otherwise be enabled TWICE (duplicate pluginId -> backend crash).
#
# Includes the `./dynamic-plugins/dist/*` refs on purpose: those plugins live
# inside the product image, so enabling them exercises the image content.
#
# Requires skopeo and jq. Usage:
#   generate-catalog-enable-values.sh <catalog-index-image> [curated-values.yaml] > enable-values.yaml
set -e

IMAGE="${1:?usage: generate-catalog-enable-values.sh <catalog-index-image> [curated-values.yaml]}"
CURATED_FILE="${2:-}"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Stable identity for a package ref: image/dist basename without tag or digest,
# plus the !plugin-name suffix when present (one OCI image can carry several
# plugins). Examples:
#   oci://ghcr.io/x/argo-cd-backend:bs_1.49__4.8.0        -> argo-cd-backend
#   oci://registry/x/argo-cd-backend@sha256:...!argocd    -> argo-cd-backend!argocd
#   ./dynamic-plugins/dist/backstage-plugin-techdocs      -> backstage-plugin-techdocs
ref_key() {
  local r="$1" suffix=""
  if [[ "$r" == *"!"* ]]; then
    suffix="!${r##*!}"
    r="${r%%!*}"
  fi
  r="${r#oci://}"
  r="${r##*/}"
  r="${r%%@*}"
  r="${r%%:*}"
  echo "${r}${suffix}"
}

curated_keys=""
if [[ -n "$CURATED_FILE" && -f "$CURATED_FILE" ]]; then
  curated_refs="$(grep -E '^[[:space:]]*-[[:space:]]+package:[[:space:]]*"?(oci://|\./dynamic-plugins/dist/)' "$CURATED_FILE" \
    | sed -E 's/^[[:space:]]*-[[:space:]]+package:[[:space:]]*"?//; s/"[[:space:]]*$//' || true)"
  while read -r ref; do
    [[ -z "$ref" ]] && continue
    curated_keys+="$(ref_key "$ref")"$'\n'
  done <<< "$curated_refs"
fi

refs="$("$DIR/catalog-index-refs.sh" "$IMAGE")"

if [[ -z "$refs" ]]; then
  echo "No packages found in dynamic-plugins.default.yaml of ${IMAGE}" >&2
  exit 1
fi

# Build the plugin entries first: emitting the `plugins:` key with an empty body
# yields `plugins: null`, which is a different shape from an empty list and would
# make the downstream yq merge fragile.
entries=""
while read -r ref; do
  [[ -z "$ref" ]] && continue
  key="$(ref_key "$ref")"
  if [[ -n "$curated_keys" ]] && grep -qxF "$key" <<< "$curated_keys"; then
    echo "# skipped (curated entry exists for '${key}'): ${ref}" >&2
    continue
  fi
  entries+="      - package: \"$ref\""$'\n'
  entries+="        disabled: false"$'\n'
done <<< "$refs"

echo "# Generated by generate-catalog-enable-values.sh for ${IMAGE}"
echo "global:"
echo "  dynamic:"
if [[ -z "$entries" ]]; then
  # Every index package already has a curated entry - nothing to add.
  echo "    plugins: []"
else
  echo "    plugins:"
  printf '%s' "$entries"
fi
