#!/bin/bash
#
# Populates dynamic-plugins-root with EVERY OCI plugin from the catalog index,
# for the plugin sanity check (playwright.plugin-sanity.config.ts).
#
# The index ships most plugins disabled by default (products opt in via their
# own config), so a plain `includes` config would install nothing. This script
# extracts the index's dynamic-plugins.default.yaml, generates an install
# config that re-enables every oci:// package it declares, and delegates the
# install to populate.sh. Local `./dynamic-plugins/dist` entries only exist
# inside the product image and are skipped by the CLI as usual.
#
# Requires skopeo and jq. Usage:
#   CATALOG_INDEX_IMAGE=quay.io/rhdh/plugin-catalog-index:next \
#     ./e2e-tests/local-harness/populate-catalog-index.sh
set -e

: "${CATALOG_INDEX_IMAGE:?CATALOG_INDEX_IMAGE must be set (e.g. quay.io/rhdh/plugin-catalog-index:next)}"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

# --- Extract dynamic-plugins.default.yaml from the catalog index OCI image.
# Layer blobs in a `skopeo copy ... dir:` layout are named by their bare sha256
# digest (no extension), so the layer list comes from manifest.json; tar
# auto-detects gzip-compressed layers. Platform overrides keep instance
# selection working on any host (multi-arch manifest lists otherwise fail on
# e.g. macOS).
skopeo copy --override-os linux --override-arch amd64 \
  "docker://${CATALOG_INDEX_IMAGE}" "dir:${workdir}/idx" > /dev/null

default_yaml=""
for digest in $(jq -r '.layers[].digest' "${workdir}/idx/manifest.json"); do
  layer="${workdir}/idx/${digest#sha256:}"
  [ -f "$layer" ] || continue
  if content="$(tar -xOf "$layer" dynamic-plugins.default.yaml 2> /dev/null)" && [ -n "$content" ]; then
    default_yaml="$content"
    break
  fi
done

if [ -z "$default_yaml" ]; then
  echo "dynamic-plugins.default.yaml not found in ${CATALOG_INDEX_IMAGE}" >&2
  exit 1
fi

# --- Collect the package refs of real (uncommented) `- package: oci://...`
# entries. Commented refs in the file must stay out - re-enabling them would
# ADD packages the index does not declare. Packages matching
# plugin-sanity-excludes.txt (documented known failures, extended-regex
# patterns) are skipped.
grep -Ev '^[[:space:]]*(#|$)' "$DIR/plugin-sanity-excludes.txt" > "$workdir/excludes.txt" || true
refs="$(echo "$default_yaml" \
  | grep -E '^[[:space:]]*-[[:space:]]+package:[[:space:]]*"?oci://' \
  | sed -E 's/^[[:space:]]*-[[:space:]]+package:[[:space:]]*"?//; s/"[[:space:]]*$//' \
  | sort -u \
  | grep -vEf "$workdir/excludes.txt" || true)"

if [ -z "$refs" ]; then
  echo "No oci:// packages found in dynamic-plugins.default.yaml of ${CATALOG_INDEX_IMAGE}" >&2
  exit 1
fi

{
  echo "# Generated by populate-catalog-index.sh for ${CATALOG_INDEX_IMAGE}"
  echo "includes:"
  echo "  - dynamic-plugins.default.yaml"
  echo "plugins:"
  while read -r ref; do
    echo "  - package: \"$ref\""
    echo "    disabled: false"
  done <<< "$refs"
} > "$workdir/dynamic-plugins.catalog-index.yaml"

echo "Enabling $(echo "$refs" | wc -l | tr -d ' ') OCI package(s) from ${CATALOG_INDEX_IMAGE}"

"$DIR/populate.sh" "$workdir/dynamic-plugins.catalog-index.yaml"
